changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## [{{.Time.Format "January 02, 2006"}}](https://github.com/OpsLevel/kubectl-opslevel/compare/{{.PreviousVersion}}...{{.Version}})'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
footerFormat: |
  ## Docker Image

    - `docker pull public.ecr.aws/opslevel/kubectl-opslevel:{{.Version}}`
kinds:
  - label: Feature
  - label: Bugfix
  - label: Security
  - label: Deprecated
  - label: Removed
  - label: Docs
newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 1
envPrefix: CHANGIE_

