# https://taskfile.dev/

version: '3'

dotenv: ['.env']

env:
  vYEAR: "v2024"
  OPSLEVEL_GO_PKG: "github.com/opslevel/opslevel-go/{{.vYEAR}}"
  OPSLEVEL_JQ_PARSER_PKG: "github.com/opslevel/opslevel-jq-parser/{{.vYEAR}}"
  OPSLEVEL_K8S_CONTROLLER_PKG: "github.com/opslevel/opslevel-k8s-controller/{{.vYEAR}}"
  SRC_DIR: "{{.TASKFILE_DIR}}/src"

tasks:
  ci:
    desc: Workflow to run in CI - MacOS only
    deps: [brew-install-jq]
    vars:
      CGO_CFLAGS:
        sh: echo -I$(dirname $(dirname $(which jq)))/include
      CGO_LDFLAGS:
        sh: echo -L$(dirname $(dirname $(which jq)))/lib
    cmds:
      - task: install-gofumpt
      - task: install-golangci-lint
      - task: lint
      - task: workspace
      - task: has-latest-opslevel-dependencies
      - task: test

  lint:
    desc: Formatting and linting
    dir: "{{.SRC_DIR}}"
    cmds:
      - test -z "$(gofumpt -d -e . | tee /dev/stderr)"
      - golangci-lint run --timeout 5m
      - nilaway -test=false -include-pkgs='github.com/opslevel/kubectl-opslevel' ./...

  fix:
    desc: Fix formatting and linting
    dir: "{{.SRC_DIR}}"
    cmds:
      - task: update-opslevel-deps
      - gofumpt -w .
      - go mod tidy
      - golangci-lint run --timeout 5m --fix
      - nilaway -fix -test=false -include-pkgs='github.com/opslevel/kubectl-opslevel' ./...

  setup:
    desc: Setup linter, formatter, etc. for local testing and CI
    cmds:
      - cmd: echo "Installing development tools..."
        silent: true
      - task: brew-install-jq
      - task: install-changie
      - task: install-gofumpt
      - task: install-golangci-lint
      - cmd: echo "Development tools installed!"
        silent: true
      - task: workspace

  test:
    desc: Run tests
    dir: "{{.SRC_DIR}}"
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./... {{ .CLI_ARGS }}
    silent: true

  update-opslevel-deps:
    desc: Update opslevel dependencies to latest release
    dir: "{{.SRC_DIR}}"
    cmds:
      - go get -u "{{.OPSLEVEL_GO_PKG}}" "{{.OPSLEVEL_JQ_PARSER_PKG}}" "{{.OPSLEVEL_K8S_CONTROLLER_PKG}}"

  workspace:
    desc: Setup workspace for cli & opslevel-go development
    dir: "{{.SRC_DIR}}"
    cmds:
      - cmd: echo "Setting up opslevel-go workspace..."
        silent: true
      - git -C .. submodule update --init --remote
      - go work init || true
      - go work use . $(git submodule | awk '{print $2}')
      - cmd: echo "submodules ready!"
        silent: true

  has-latest-opslevel-dependencies:
    desc: Check if opslevel dependencies are up to date in go.mod
    dir: "{{.SRC_DIR}}"
    silent: true
    cmds:
      - defer: { task: undo-ignore-go-work-files }
      - task: tmp-ignore-go-work-file
      - for: [ "{{.OPSLEVEL_GO_PKG}}", "{{.OPSLEVEL_JQ_PARSER_PKG}}", "{{.OPSLEVEL_K8S_CONTROLLER_PKG}}" ]
        task: has-latest-opslevel-dep
        vars:
          OPSLEVEL_PKG: "{{.ITEM}}"

  # internal (not directly called) tasks

  tmp-ignore-go-work-file:
    dir: "{{.SRC_DIR}}"
    internal: true
    silent: true
    cmds:
      - if [[ -f "go.work" ]]; then mv "go.work"  "tmp_go.work"; fi

  undo-ignore-go-work-files:
    dir: "{{.SRC_DIR}}"
    internal: true
    silent: true
    cmds:
      - if [[ -f "tmp_go.work" ]]; then mv "tmp_go.work" "go.work"; fi

  has-latest-opslevel-dep:
    dir: "{{.SRC_DIR}}"
    internal: true
    silent: true
    vars:
      LATEST_OPSLEVEL_PKG_VERSION:
        sh: go list -u -m -versions {{.OPSLEVEL_PKG}} | awk '{print $NF}'
    cmds:
      - |-
        if [[ {{.LATEST_OPSLEVEL_PKG_VERSION}} == $(go list -m --json '{{.OPSLEVEL_PKG}}' | jq -r '.Version') ]]; then
          echo "Using latest version of {{.OPSLEVEL_PKG}} - {{.LATEST_OPSLEVEL_PKG_VERSION}}";
        else
          echo "WARNING: current version of {{.OPSLEVEL_PKG}} is behind '{{.LATEST_OPSLEVEL_PKG_VERSION}}'"
          echo "Run 'task fix' to get latest version"
          exit 1
        fi
    requires:
      vars: [OPSLEVEL_PKG]

  brew-install-jq:
    internal: true
    platforms: [darwin]
    cmds: ["which jq > /dev/null || brew install jq"]
    preconditions:
      - sh: 'which brew'
        msg: '"brew" needed to install "jq"- see https://brew.sh'

  go-install-tool:
    desc: go install '{{.GO_TOOL}}' and set GOBIN if not set
    internal: true
    silent: true
    vars:
      IS_TOOL_INSTALLED:
        sh: which {{.GO_TOOL}} > /dev/null || echo "1"
    cmds:
      - test -z "{{.IS_TOOL_INSTALLED}}" || echo "Installing {{.GO_TOOL}}..."
      - test -z "{{.IS_TOOL_INSTALLED}}" || go install {{.GO_TOOL_PATH}}
      - test -n $(go env GOBIN) || go env -w GOBIN=$(go env GOPATH)/bin
      - echo "  '{{.GO_TOOL}}' is installed."
    requires:
      vars: [GO_TOOL, GO_TOOL_PATH]

  install-changie:
    desc: go install "changie"
    internal: true
    cmds:
      - task: go-install-tool
        vars: { GO_TOOL: "changie", GO_TOOL_PATH: "github.com/miniscruff/changie@latest" }

  install-gofumpt:
    desc: go install "gofumpt"
    internal: true
    cmds:
      - task: go-install-tool
        vars: { GO_TOOL: "gofumpt", GO_TOOL_PATH: "mvdan.cc/gofumpt@latest" }

  install-golangci-lint:
    desc: go install "golangci-lint"
    internal: true
    cmds:
      - task: go-install-tool
        vars: { GO_TOOL: "golangci-lint", GO_TOOL_PATH: "github.com/golangci/golangci-lint/cmd/golangci-lint@latest" }
