project_name: kubectl-opslevel
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - darwin
    goarch:
      - amd64
    binary: '{{ .ProjectName }}'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
brews:
  - name: kubectl
    homepage: "https://www.opslevel.com/"
    description: "Command line tool that enables you to import & reconcile services with OpsLevel"
    license: "MIT"
    folder: Formula
    dependencies:
      - name: go
      - name: jq
    install: |
      ENV["CGO_ENABLED"] = "1"
      ENV["CGO_CFLAGS"] = "-I#{Formula["jq"].opt_include}"
      ENV["CGO_LDFLAGS"] = "-L#{Formula["jq"].opt_lib}"

      system "go", "build", *std_go_args(output: bin/"kubectl-opslevel", ldflags: "-s -w"), "./src"
    test: |
      system "#{bin}/kubectl-opslevel", "version"
    repository:
      owner: opslevel
      name: homebrew-tap
      token: "{{ .Env.ORG_GITHUB_TOKEN }}"
checksum:
  name_template: '{{ .ProjectName }}.sha256'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: desc
  filters:
    exclude:
      - "^Merge"
release:
  prerelease: auto
