project_name: kubectl-opslevel
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
      - CGO_CFLAGS="-I/libjq/include"
      - CGO_LDFLAGS="-L/libjq/lib"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm'
      - goos: windows
        goarch: 'arm64'
    binary: '{{ .ProjectName }}'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: kubectl
    homepage: "https://www.opslevel.com/"
    description: "Command line tool that enables you to import & reconcile services with OpsLevel"
    license: "MIT"
    folder: Formula
    dependencies:
      - name: jq
    install: |
      bin.install "kubectl-opslevel"
    test: |
      system "#{bin}/kubectl-opslevel version"
    repository:
      owner: opslevel
      name: homebrew-tap
      token: "{{ .Env.ORG_GITHUB_TOKEN }}"
checksum:
  name_template: '{{ .ProjectName }}.sha256'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: desc
  filters:
    exclude:
      - "^Merge"
release:
  prerelease: auto
