FROM flant/jq:b6be13d5-glibc as libjq

FROM golang:1.21 AS builder
WORKDIR /src

# Cache-friendly download of go dependencies.
ADD go.mod go.sum /src/
RUN go mod download

COPY --from=libjq /libjq /libjq
COPY . /src

RUN CGO_ENABLED=1 \
    CGO_CFLAGS="-I/libjq/include" \
    CGO_LDFLAGS="-L/libjq/lib" \
    go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...