apiVersion: v1
kind: Namespace
metadata:
  name: opslevel
  labels:
    {{- include "opslevel-sync.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}