apiVersion: v1
kind: Secret
metadata:
  name: api-token
  labels:
    {{- include "opslevel-sync.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: opaque
data:
  OL_APITOKEN: {{ .Values.apitoken | b64enc | quote }}