apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opslevel-sync.serviceAccountName" . }}
  labels:
    {{- include "opslevel-sync.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sync
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - networking
  resources: 
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sync
subjects:
- kind: ServiceAccount
  name: {{ include "opslevel-sync.serviceAccountName" . }}
  namespace: opslevel
roleRef:
  kind: ClusterRole
  name: sync
  apiGroup: rbac.authorization.k8s.io