name: "Release Docker"

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
      - name: Fetch All Tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Set Release Version
        id: version
        run: |
          echo "RELEASE_VERSION=$(date +v%Y.%-m.%-d)" >> $GITHUB_OUTPUT
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Login to Public ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_PUBLIC_REGISTRY }}
          username: ${{ secrets.ECR_PUBLIC_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_PUBLIC_AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1
      - name: Docker Build And Push
        env:
          IMAGE: "public.ecr.aws/opslevel/kubectl-opslevel"
          TAG: ${{ steps.version.outputs.RELEASE_VERSION }}
        run: |
          cd ./src
          docker build -t "${IMAGE}:latest" -t "${IMAGE}:${TAG}" .
          docker push "${IMAGE}:latest"
          docker push "${IMAGE}:${TAG}"
      - name: Report Release To OpsLevel
        uses: opslevel/report-deploy-github-action@v0.7.0
        with:
          integration_url: ${{ secrets.DEPLOY_INTEGRATION_URL }}
          service: "opslevel_kubernetes_sync"
