name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Run Tests
        run: |-
          docker build -t testing:latest -f Dockerfile --target tester .
          id=$(docker create testing:latest)
          docker cp $id:/src/coverage.txt - > coverage.txt  
          docker rm -v $id
      - name: Upload Coverage
        run: |-
          cd src/
          bash <(curl -s https://codecov.io/bash)
