name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Install libjq
        run: |
          sudo apt-get update -y
          sudo apt list -a libjq-dev
          sudo apt-get install -y build-essential libjq-dev
      - name: Run Tests
        run: |-
          cd src/
          go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload Coverage
        run: |-
          cd src/
          bash <(curl -s https://codecov.io/bash)
