name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
      - name: Run quality checks and test code
        run: task ci
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./src/coverage.txt
          fail_ci_if_error: false
          verbose: true
